---
main:
  logback-config-file: "${LOGBACK_CONFIG_FILE:-logback.xml}"
  application-id: "${APPLICATION_ID:-groceries-recommender}"
  create-topics: "${MAIN_CREATE_TOPICS:-true}"
  start-simulator: "${MAIN_START_SIMULATOR:-true}"
  port: "${PORT:-8080}"
topics:
  name:
    products: "groceries.products.v1"
    orders: "groceries.orders.v1"
    related-products: "groceries.related-products.v1"
  create:
    products:
      partitions: 1
      replication-factor: 1
      configs:
        cleanup.policy: "compact"
        retention.ms: -1
    orders:
      partitions: 1
      replication-factor: 1
      configs:
        cleanup.policy: "compact"
        retention.ms: -1
    related-products:
      partitions: 1
      replication-factor: 1
      configs:
        cleanup.policy: "compact"
        retention.ms: -1
kafka:
  application.id: "${APPLICATION_ID:-groceries-recommender}${APPLICATION_VERSION:-_v1}"
  bootstrap.servers: "${KAFKA_BOOTSTRAP_SERVERS:-localhost:19092}"
  auto.offset.reset: "earliest"
  default.key.serde: "com.github.avrokotlin.avro4k.kafka.confluent.ReflectAvro4kKafkaSerde"
  default.value.serde: "com.github.avrokotlin.avro4k.kafka.confluent.ReflectAvro4kKafkaSerde"
  session.timeout.ms: "45000"
  request.timeout.ms: "20000"
  retry.backoff.ms: "500"
  security.protocol: "${KAFKA_SECURITY_PROTOCOL:-PLAINTEXT}"
  schema.registry.url: "${KAFKA_SCHEMA_REGISTRY_URL:-http://localhost:8081}"
  schema.registry.basic.auth.user.info: "${KAFKA_SCHEMA_REGISTRY_AUTH:-}"
  allow.auto.create.topics: "false"
  auto.register.schemas: "true"
  rocksdb.config.setter: "io.github.marcgoosen.groceries.shared.kafka.BoundedMemoryRocksDBConfig"
  rocksdb.total_offheap_size_mb: "${ROCKSDB_TOTAL_OFF_HEAP_SIZE_MB:-16}"
  rocksdb.total_memtable_mb: "${ROCKSDB_TOTAL_MEMTABLE_MB:-16}"
  rocksdb.block_size_kb: "${ROCKSDB_BLOCK_SIZE_KB:-16}"
  rocksdb.n_memtables: "${ROCKSDB_N_MEMTABLES:-2}"
  rocksdb.memtable_size_mb: "${ROCKSDB_MEMTABLE_SIZE_MB:-64}"
  commit.interval.ms: "${KAFKA_COMMIT_INTERVAL_MS:-100}"
  poll.ms: "${KAFKA_POLL_MS:-100}"
  topology.optimization: "all"
  ensure.explicit.internal.resource.naming: "true"
